### ISSUE TITLE
gui run bug

### ISSUE THREAD

**Issue by hagorms** [euratom-software/calcam#19]
after installation and running gui, no buttons are active (opens and closes a window with no log/output) 
![image](https://user-images.githubusercontent.com/12120066/37468857-496f880c-2864-11e8-8925-ae0fadc25c64.png)

**Comment by hagorms** [comment]
It also happens, if I do start gui from the console/pycharm

**Comment by ssilburn** [comment]
Hi, please can you let me know what versions of Python, VTK and PyQt you're using, and / or what Python distribution?

**Comment by ssilburn** [comment]
Hi, this was due to a bug in some exception handling code (probably a hangover related to Python 2 / 3 compatibility).

It should now be fixed in commit  ea1aa9a  - please pull the latest version from master and try it again.

**Comment by hagorms** [comment]
Hi. Thank you. I was at the conference for these 2 days, so i didnt have an
access to working machine. Thank you, i will test tmr

18 мар. 2018 г. 12:18 ПП пользователь "Scott Silburn" <
notifications@github.com> написал:

**Comment by hagorms** [comment]
Closed. Well done. Thank you!
