### ISSUE TITLE
Opencv version 4 not supported

### ISSUE THREAD

**Issue by nick-walkden** [euratom-software/calcam#35]
I think this just needs a fix to the if statement in the do_fit function in the calibration class.

**Comment by ssilburn** [comment]
Thanks Nick, hadn't spotted this! Now changed on the master branch. In general I should check if there are any other issues with changes from OpenCV 3 > 4; I haven't done any testing of that at all myself yet. I'll leave this issue open to remind me.

**Comment by nick-walkden** [comment]
Great, thanks! I'm sure I'll run into more of these if they exist in the code so i'll document them here when I do.

**Comment by ssilburn** [comment]
Now fixed on the master branch and will be in the 2.2.0 release :)
