### ISSUE TITLE
Segmentation fault on initialization of Virtual calib editor and manual alignment editor on Mac-Os

### ISSUE THREAD

**Issue by nick-walkden** [euratom-software/calcam#36]
I believe this is fairly specific to Mac-OS. I am using Mac-OS 10.14.2, and VTK 8.1.2

I think the segfault occurs in instances where the editor attempts to pre-load the CAD model whilst rendering the initial window. 

I can prevent the segfault by commenting out the two calls

https://github.com/euratom-software/calcam/blob/9a3982307985bb7aeb3fcd0fc4e8951a6e5aa9a4/calcam/gui/virtual_calib.py#L222

and 

https://github.com/euratom-software/calcam/blob/9a3982307985bb7aeb3fcd0fc4e8951a6e5aa9a4/calcam/gui/virtual_calib.py#L225

however this is just treating a symptom. I think the root cause must be in some issue that VTK has on Mac-Os with the initial render in these two cases, and it seems like its related to the cases where it attempts to preload the cad model (I think....)

Is it possible to prevent these two editors from pre-loading the CAD model?

**Comment by ssilburn** [comment]
This is now fixed on the master branch  & will be in release 2.2.0 - was due to somewhat careless line ordering in the __init__ of the GUI classes; it was trying to refresh the VTK objects before they were properly initialised. Not sure why it only caused segfaults on OSX though.
