### ISSUE TITLE
Enable projection of points outside pointfield

### ISSUE THREAD

**Issue by TomFarley** [euratom-software/calcam#4]
Would be useful to have keyword option to project points outside of image - ie extrapolate and override line 740 in fitting.py .

**Comment by TomFarley** [comment]
Added branch tfarley for merging

**Comment by ssilburn** [comment]
Hi Tom, an 'OutOfFrame' keyword argument has been implemented in CalibResults.project_points based on your edits as of commit ba47d90e373471442981a3f0dcb5af4e88d63670.
