### ISSUE TITLE
Deleting default viewport causes exception

### ISSUE THREAD

**Issue by haisongdong-harrison** [euratom-software/calcam#68]
## Issue:
When using the GUI to add a new model definition, if I have only added a default view, trying to remove it will cause an exception to be thrown:

```
Traceback (most recent call last):
  File "/home/harrison/anaconda3/envs/dev_env/lib/python3.6/site-packages/Calcam-2.6.1-py3.6.egg/calcam/gui/cad_edit.py", line 742, in remove_view
    self.cadmodel.views.pop(selected_view)
KeyError: 'View*'
```

If I add another view and set it as default before deleting the original default view, it would be fine.

By the way, the `X` close button in the error prompt window doesn't really work, and you must click one of the two bigger buttons below to close the window, but that's a trivial bug compared to the other one.
![image](https://user-images.githubusercontent.com/13168445/112922106-df98bf80-9146-11eb-9ed9-d613920e4af8.png)

I'm on Ubuntu 18.04 with Python 3.6.7
CalCam hash 38cbd80(current head of `master`)

**Comment by ssilburn** [comment]
Hi, thanks for reporting this. It should now be fixed on `master`, and also the non-functioning close button is removed from the exception window (and wording of the main buttons changed slightly - I realise it was not clear if the "close without saving" button would close the whole GUI). All the best!
