### ISSUE TITLE
Add Vertical FOV option to Virtual Calibration Editor

### ISSUE THREAD

**Issue by rdoyle45** [euratom-software/calcam#85]
Is it possible to get the "Vertical FOV" option that is in "Calibration Tool" added to the Virtual Calibration Editor for situations when focal length etc might not be known but FOV is?

**Comment by ssilburn** [comment]
OK, I'll see if I can fit a new box for it next to the focal length one so you can use either to set the FOV.

**Comment by ssilburn** [comment]
Hi @rdoyle45 - if you're in a hurry for this, it's now done on the "ss_dev" branch so you can use it now - I want to do some more checks / additions on that branch and then I'll merge it on to master & release.

**Comment by rdoyle45** [comment]
Great thanks Scott. Much appreciated.
