### ISSUE TITLE
Error while fitting with checkerboards

### ISSUE THREAD

**Issue by perek42** [euratom-software/calcam#99]
Newer versions of numpy ( 1.24.2) cause the error below. It was solved for me by downgrading it to numpy==1.21.6

Cheers, 
Artur

DIAGNOSTIC INFORMATION
----------------------

Platform:       darwin
Python version: 3.10.10 (main, Feb 16 2023, 02:49:39) [Clang 14.0.0 (clang-1400.0.29.202)]
Calcam version: 2.10.0
VTK version:    9.2.6
OpenCV version: 4.6.0
PyQt version:   5.15.7

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/calcam-2.10.0-py3.10.egg/calcam/gui/fitting_calib.py", line 1233, in do_fit
    self.calibration.set_fit(subview, self.fitters[subview].do_fit())
  File "/opt/homebrew/lib/python3.10/site-packages/calcam-2.10.0-py3.10.egg/calcam/calibration.py", line 2437, in do_fit
    obj_points = np.array(obj_points)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (18,) + inhomogeneous part.

**Comment by ssilburn** [comment]
Thanks for reporting this Artur! Now fixed on the master branch, release coming soon!

**Comment by ssilburn** [comment]
Now fixed in release v2.11

**Comment by perek42** [comment]
Thanks a lot!
